<a href="https://colab.research.google.com/github/seungheekk/Big-Data-Analysis-Programming/blob/main/03w_numpy_handle_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 03 과학용 컴퓨팅 패키지 numpy

## 01 패키지 numpy 개요와 자료형 ndarray

In [ ]:
import numpy as np
np.linspace(2, 3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
(3-1)/(50-1)

0.04081632653061224

In [ ]:
np.linspace(2, 3, 2)

array([2., 3.])

In [ ]:
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

In [ ]:
np.linspace(2, 3, 3, retstep = True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [ ]:
a = np.linspace(2, 3, 3, retstep = True)
float(a[1])

0.5

In [ ]:
np.linspace(2, 3, 3, retstep = True, endpoint=False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [ ]:
(3-2)/3

0.3333333333333333

In [ ]:
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

## numpy 주요 함수

In [ ]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((5, ), dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros(2, 3)

TypeError: Cannot interpret '3' as a data type

In [ ]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.arange(4).reshape(4, 1)

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
np.full((4, 3), np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### 고급 색인

In [ ]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[ [2] ]

array([2])

In [ ]:
x[ [2, 3] ]

array([2, 3])

In [ ]:
x[ 2, 3 ]

np.int64(19)

In [ ]:
x[ [2, 3, 2, 5, 8] ]

array([2, 3, 2, 5, 8])

In [ ]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
int(x[0, 1])

1

In [ ]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [ ]:
x[..., 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[0, 1]

np.int64(1)

In [ ]:
x[ [0], [1] ]

array([1])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0, 1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[ [1, 3, 5] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x[ [1, 3, 5], : ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [1, 3], [2, 2] ]

array([10, 26])

In [ ]:
x[ [1, 3], [2] ]

array([10, 26])

In [ ]:
x[ [1, 3], [2, 3] ]

array([10, 27])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0, 2, 4], [1] ]

array([ 1, 17, 33])

In [ ]:
x[ [0, 2, 4], 1 ]

array([ 1, 17, 33])

In [ ]:
x[ [0, 2, 4], :2 ]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
x[ [0, 2, 4], [1, 1, 1] ]

array([ 1, 17, 33])

In [ ]:
x[ [0, 2, 4], [1, 1] ]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [ ]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[[2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [ ]:
a[np.arange(2, 4)][:, [1, 1, 1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [ ]:
a[np.arange(2, 4)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [ ]:
a[[2, 3]][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [ ]:
a[np.arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[[2, 3, 4]][:, [-1, -2, -3, -4, -5, -6, -7]]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [ ]:
a[[2, 3, 4]][:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

###종료

다차원 배열 ndarray

In [ ]:
import numpy as np
a = np.ndarray((2,3))
a

array([[4.29534162e-315, 0.00000000e+000, 6.79038653e-313],
       [6.79038653e-313, 6.79038654e-313, 1.97345609e-312]])

In [ ]:
import numpy as np
a = np.ndarray((3,2), dtype=int)
a

array([[   869386822,            0],
       [137438953516, 137438953523],
       [137438953565, 399431958580]])

In [ ]:
a = np.ndarray((3,2),int)
a

array([[      872367826,               0],
       [132623192809680, 132623192808272],
       [132623192806160,               0]])

In [ ]:
import numpy as np
a = np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [ ]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


###문자열 자료형

In [ ]:
np.array([1, 'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np

unicode_array = np.array(['가나다','라마바','사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
unicode_array = np.array(['가나다라마'*7, '라마바','사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

###numpy.arange()

In [ ]:
import numpy as np

print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [ ]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(3, 7, 2))

[0. 1.]
[2. 3. 4. 5. 6.]
[3 5]


In [ ]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


###배열의 모양을 바꾸는 reshape()

In [103]:
import numpy as np

a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
np.reshape(a, (2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [105]:
np.reshape(a,(3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

### 함수 linspace()

In [106]:
np.linspace(2.0,3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [107]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [108]:
print((3-2)/(50-1))

0.02040816326530612


In [110]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [111]:
print((3-2)/ 50)

0.02


In [113]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [116]:
np.linspace(2.0, 3.0, num = 5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

###내장함수 np.zeros()

In [118]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [119]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

###원소가 모두 1.0인 배열을 생성하는 ones()

In [120]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [121]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

###numpy.eye()

In [122]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [124]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [125]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [126]:
b = np.eye(3, 4, -1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
###numpy.full(shape,fill_value)

In [128]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [129]:
np.full([2, 3],(1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [130]:
np.full([2, 3], (1,2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [131]:
np.full([3,4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [133]:
np.full([4,3], fill_value=np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [134]:
#지정한 모양의 배열을 생성하는 numpy.empty(shape)

In [135]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [136]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [140]:
np.empty([2, 3], dtype=int)

array([[      916180775,               0, 132622789602240],
       [132622798189568, 132622789602304, 132622798189952]])

In [141]:
#원소값이 0인 주어진 형태의 배열을 생성하는 zeros_like(a)

In [142]:
import numpy as np

a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [143]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
#원소값이 1인 주어진 형태의 배열을 생성하는 ones_like()

In [148]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [149]:
#원소값이 주어진 값이며 주어진 형태의 배열을 생성하는 full_like()

In [150]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

###배열과 스칼라와의 연산

In [154]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [155]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


###배열과 배열의 연산

In [156]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [158]:
b = np.full_like(a,[1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [159]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [160]:
#복합 대입 연산자도 지원

In [161]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [166]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [167]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [168]:
b += a
b

array([0.5, 2.5, 4.5, 6.5])

In [169]:
# 다양한 배열의 곱 연산자

In [177]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [179]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [180]:
a @ b

array([[12,  6],
       [12,  6]])

In [181]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [182]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [183]:
import numpy as np
print(np.matmul(a,b))
print(np.matmul(b,a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [184]:
# 배열 함수

In [185]:
a = np.array([[10, 20], [5,8],[1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [187]:
a.sum()

np.int64(46)

In [188]:
a.sum(axis=0)

array([16, 30])

In [189]:
a.sum(axis=1)

array([30, 13,  3])

In [190]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis =1))

46
[16 30]
[30 13  3]


In [191]:
# 배열 함수

In [192]:
a = np.array([[3, 5, 8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [193]:
#일차원으로 펼쳐서 계산
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [194]:
a.cumsum(axis=0) #시험예상, 행을 따라 세로로 합산

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [195]:
a.cumsum(axis=1) #시험예상, 열을 따라 가로로 합산

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [196]:
#다양한 이항 연산 범용 함수

In [197]:
import numpy as np
a = np.array([1, 4,9])
a

array([1, 4, 9])

In [198]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [199]:
np.add(a, b)

array([ 3,  6, 11])

In [200]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [202]:
np.power(a,b)

array([ 1, 16, 81])

In [ ]:
#1차원 배열의 첨자와 슬라이싱

In [209]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [210]:
print(a[3])
print(a[-2])

9
64


In [211]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [212]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [ ]:
# 역순과 대입

In [213]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [214]:
a[::-2]

array([81, 49, 25,  9,  1])

In [216]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [217]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [218]:
a[2:5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [219]:
a[2:5] = 10
a

array([ 0,  1, 10, 10, 10, 25, 36, 49, 64, 81])

In [ ]:
# 2차원 배열의 첨자와 슬라이싱

In [220]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [221]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [222]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [223]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [224]:
a[-2,]

array([18, 19, 20, 21, 22, 23])

In [225]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [226]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [230]:
a[, 1]

SyntaxError: invalid syntax (3063698125.py, line 1)

In [231]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [232]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [233]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [234]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [237]:
a[2, 4]

np.int64(16)

In [238]:
a[2][4]

np.int64(16)

In [239]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [240]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [241]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [243]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [244]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [245]:
#마지막행과 열을 제외한 배열 반환
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [246]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [247]:
a [1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [248]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [249]:
a[:, 1,1]

array([ 5, 17])

In [250]:
a[:, :,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [251]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [252]:
a[1, ..., 1]

array([13, 17, 21])

In [253]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [254]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 1차원 배열로 만드는 ndarray.ravel()

In [257]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [261]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# np.transpose(a)와 a.transpose(), a.T

In [263]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [264]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [265]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [266]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 3차원 배열의 전치 행렬

In [267]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [268]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [269]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [270]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [271]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [272]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [ ]:
# np.swapaxes(a, axis1, axis2)

In [273]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [274]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [275]:
y = np.swapaxes(x, 1,0)
y

array([[7],
       [8],
       [9]])

In [276]:
y[0,0] = 10
x

array([[10,  8,  9]])

In [ ]:
# 3차원 배열에서 swapaxes()

In [277]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [278]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [279]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [ ]:
# 보기

In [280]:
org =np.arange(5)
org

array([0, 1, 2, 3, 4])

In [281]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [282]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [283]:
org

array([  0,   1, 200,   3,   4])

In [ ]:
# 복사

In [284]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [285]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [286]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [287]:
org

array([0, 1, 2, 3, 4])

In [288]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [289]:
y = x.reshape(2, 3) #view를 반환
y

array([[0, 1, 2],
       [3, 4, 5]])

In [290]:
print(x.base)

None


In [291]:
y.base

array([0, 1, 2, 3, 4, 5])

In [292]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [293]:
c = z.copy()
print(c.base)

None


In [294]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [295]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [296]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [297]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [298]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [ ]:
# 보기 (뷰, view)와 얕은 복사

In [299]:
a = np.array([[1, 2, 3], [4,5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [300]:
b = a
b is a

True

In [301]:
print(id(a))
print(id(b))

132622777173072
132622777173072


In [302]:
print(a.base)
print(b.base)

None
None


In [303]:
b[0, 0 ] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [304]:
c = a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [305]:
print(id(a))
print(id(c))
print(c.base)

132622777173072
132622777173552
None


In [306]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [307]:
print(id(a))
print(id(v))

132622777173072
132622777172592


In [308]:
v[0,1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [309]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

### 브로드 캐스팅

In [310]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [311]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [312]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [313]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [314]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [315]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

### 하나의 배열이 2차원으로 다른 배열 행수와 같은 구조의 브로드캐스팅

In [316]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [317]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [318]:
# 소수점 이하 자릿수를 2 자리로 설정
np.set_printoptions(precision=2)

In [319]:
x / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [320]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [321]:
# 행 또는 열이 1인 두 배열의 브로드 캐스팅

In [323]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [324]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [325]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [326]:
x / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [327]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [328]:
y = arange(1, 3)
y

array([1, 2])

In [329]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [330]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [331]:
# 상수 np.newaxis 활용한 배열 차원 확장(즏가)

In [332]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [333]:
np.newaxis is None

True

In [334]:
#차수를 증가
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [335]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [336]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [337]:
a.shape

(4, 1)

In [338]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [339]:
from numpy import array

b = array([1, 2, 3])
b

array([1, 2, 3])

In [340]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [341]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

### 고급 색인

In [342]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [343]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [344]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [345]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [346]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [347]:
# 2차원 배열의 색인

In [348]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [349]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [352]:
x[0, 1]

np.int64(1)

In [353]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [354]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [355]:
x[[0],[1]]

array([1])

In [356]:
# 0, 1행
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [357]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [358]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [359]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [360]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [361]:
# 첨자 [1, 2] 과 [3,2]에 해당하는 10과 26
x[[1, 3], [2,2]]

array([10, 26])

In [363]:
# 위와 동일
x[[1, 3], [2]]

array([10, 26])

In [364]:
# 1, 3행의 2열
x[[1, 3], 2]

array([10, 26])

In [365]:
# 행과 열 참조 매핑

In [366]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [367]:
x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

In [368]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [369]:
x[array([0, 2, 4]), :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [370]:
from numpy import array
x[array([0, 2, 4]),array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [371]:
# 기본 색인 방법

In [372]:
from numpy import arange
a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [373]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [374]:
a[arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [375]:
# 고급 색인 방법

In [376]:
from numpy import arange

a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [377]:
a[arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [379]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [380]:
a[arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [381]:
a[arange(2, 5)][:,arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])