<a href="https://colab.research.google.com/github/seungheekk/Big-Data-Analysis-Programming/blob/main/04w_array_stack_split_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np    #23

a= np.arange(1, 13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [ ]:
import numpy as np
np.hstack((a, np.expand_dims(c, axis=1)))   #

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack( (a, c))   #위랑 동일

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5 ,6])   #늘리고 밑에 처럼 합침.

np.c_[a,b]   #c의 의미는 칼람

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack( (a, b))   #1차원일 때 동일

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.array( [[1,2,3]])
y = np.array([[4, 5,6]])
x

array([[1, 2, 3]])

In [ ]:
y

array([[4, 5, 6]])

In [ ]:
x.shape, y.shape

((1, 3), (1, 3))

In [ ]:
np.column_stack( (x,y) )

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x, 10,20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack( (x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
# numpy다양한 함수

In [ ]:
import numpy as np
rg = np.random.default_rng(12345) #시드 값을 둬서 맨 처음ㅇ
rg.random()  #0 [0, 1]0은 포함 1은 포함 안한 실수

0.22733602246716966

In [ ]:
rg.random()

0.31675833970975287

In [ ]:
rg.random(5)

array([0.79736546, 0.67625467, 0.39110955, 0.33281393, 0.59830875])

In [ ]:
rg.random((2, 3, 4))

array([[[0.18673419, 0.67275604, 0.94180287, 0.24824571],
        [0.94888115, 0.66723745, 0.09589794, 0.44183967],
        [0.88647992, 0.6974535 , 0.32647286, 0.73392816]],

       [[0.22013496, 0.08159457, 0.1598956 , 0.34010018],
        [0.46519315, 0.26642103, 0.8157764 , 0.19329439],
        [0.12946908, 0.09166475, 0.59856801, 0.8547419 ]]])

In [ ]:
rg.random(5)

array([0.60162124, 0.93198836, 0.72478136, 0.86055132, 0.9293378 ])

In [ ]:
rg.random(5)

array([0.54618601, 0.93767296, 0.49498794, 0.27377318, 0.45177871])

In [ ]:
import numpy as np
rg = np.random.default_rng(1) #시드 값을 둬서 맨 처음ㅇ
rg.integers(0, 10, 3)         # [0, 10] 정수 난수 0은 low ,higth하나 적은 수, 3: 사이즈

array([4, 5, 7])

In [ ]:
rg.integers(0, high=20, size=(3,4))

array([[19,  0,  2, 16],
       [18,  4,  6, 17],
       [ 8,  5, 16,  5]])

In [ ]:
rg.integers(1, 7, (3, 4))

array([[3, 4, 4, 1],
       [1, 6, 5, 6],
       [4, 5, 2, 3]])

In [ ]:
#wjdrb qns포 생성
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(3) # 표준 정규분포 실수 난수

array([0.34558419, 0.82161814, 0.33043708])

In [ ]:
rg.standard_normal((3,4)) # 표준 정규분포 실수 난수

array([[-1.30315723,  0.90535587,  0.44637457, -0.53695324],
       [ 0.5811181 ,  0.3645724 ,  0.2941325 ,  0.02842224],
       [ 0.54671299, -0.73645409, -0.16290995, -0.48211931]])

##배열 결합 연습

In [ ]:
a = np.arange(1, 4) #한 줄 복사 쉬프트+ 알트 +아래방향키
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
p = np.arange(1, 7).reshape(2, 3) #한 줄 복사 쉬프트+ 알트 +아래방향키
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)
p,q,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
np.vstack( (a, b, c)) # 1D --> 2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.vstack( (p, q, r)) # 1D --> 2D 5장 6장에 1,2 8장까지 중간고사 시험범위

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.hstack( ( a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
np.hstack( (p, q, r)) #2D --> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
np.column_stack((a, b, c)) #1D --> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack((p, q, r)) #2D -->2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a, b, c), axis=-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
p,q,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
np.concatenate((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p, q, r), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p, q, r), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p, q, r), axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p, q,r), axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [ ]:
np.c_[a, b, c] # 1D --> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack((a, b, c)) # 1D --> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack([a, b, c]) # 1D --> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack(a, b,c)

TypeError: column_stack() takes 1 positional argument but 3 were given

In [ ]:
np.c_[p,q, r] #2D --> 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.c_[p,q,r] #2D-->2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.r_[a, b, c] # 1D-->1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.r_[p,q, r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.vstack( (p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis],y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
np.column_stack == np.hstack

False

In [72]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [73]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [78]:
np.row_stack((a, b))

/tmp/ipykernel_734/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [89]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5,6])

In [90]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [91]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [92]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [94]:
import numpy as np
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [97]:
z = np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [98]:
np. concatenate ((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [99]:
np. concatenate ((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [101]:
# 평면화 작업 후 연결
np. concatenate ((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [104]:
import numpy as np
a= np.array([1,2,3])
a

array([1, 2, 3])

In [108]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [109]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.stack((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [112]:
np.stack((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [113]:
np.arange(1,19).reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [114]:
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [115]:
x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [116]:
y=np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [117]:
z=np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [118]:
ax0=np.stack((x,y,z),axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [119]:
ax0.shape

(3, 2, 3)

In [120]:
x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [121]:
y=np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [123]:
z=np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [124]:
ax1=np.stack((x,y,z),axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [125]:
ax1.shape

(2, 3, 3)

In [126]:
x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [127]:
y=np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [128]:
x=np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [148]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [150]:
print(x,'\n')

[[0 1 2]
 [3 4 5]] 



In [151]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [152]:
print(y,'\n')

[[10 11 12]
 [13 14 15]] 



In [146]:
print(x, '\n')

[[20 21 22]
 [23 24 25]] 



In [153]:
z = np.arange(20,26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [154]:
print(z,'\n')

[[20 21 22]
 [23 24 25]] 



In [156]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [157]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [158]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [159]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [160]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [161]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [162]:
np.expand_dims(x, axis= 2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [163]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [164]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [166]:
np.expand_dims(x, axis= 2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [167]:
np.expand_dims(y, axis= 2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [168]:
np.expand_dims(z,axis= 2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [169]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [175]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [177]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [178]:
np.row_stack((a, b))

/tmp/ipykernel_734/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [179]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [181]:
import numpy as np
#두 개의 1D 배열을 열 방향으로 결합
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.c_[a, b]
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [182]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [183]:
np.c_[x,y]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [184]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [185]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [186]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [187]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [188]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [189]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [190]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [191]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [193]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [194]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [195]:
np.row_stack((a, b))

/tmp/ipykernel_734/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [196]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [197]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [198]:
np.r_[-1:1:6j, [0*2, 5, 6]]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  5. ,  6. ])

In [199]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [200]:
a = np.array([[0, 1, 2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [201]:
np.r_[a, a, a] #concatenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [202]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [203]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [204]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [205]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [206]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [207]:
import numpy as np
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [208]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [210]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [211]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [212]:
#다차원 배열 np.split(ary, n, axis = 1)
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [213]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [214]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [217]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [218]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [219]:
np.split(b,[2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [220]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [221]:
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [222]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [223]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [224]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [226]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [227]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [228]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [229]:
a[:,:3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [230]:
a[:,8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [231]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [232]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [233]:
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [234]:
a = np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [235]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [236]:
a[:1, :]

array([[0, 1, 2]])

In [237]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [238]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

In [243]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [244]:
np.split(x, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [245]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [246]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [247]:
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [248]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [249]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [251]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [252]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [254]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [255]:
np.hsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [256]:
np.split(x, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [257]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [258]:
np.hsplit(x, [1,3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [259]:
import numpy as np
rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x786A23C1B680

In [260]:
r = rg.random()
r

0.22733602246716966

In [261]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [262]:
rg.random((4, 3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [263]:
import numpy as np
rg = np.random.default_rng(12345)
r = rg.integers(low = 0, high=10, size = 3)
r

array([6, 2, 7])

In [265]:
rg.integers(1, 7,(3, 4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [266]:
import numpy as np

rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [267]:
rg.standard_normal((4, 3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])